# build environment
FROM node:9-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY . /app
RUN npm install
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /assets/bundles/index.html /usr/share/nginx/html/
COPY --from=build /assets/bundles/ /usr/share/nginx/html/static/public_bundles/
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
