version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - $PWD/pg/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
  backend:
    build: backend
    #command: python manage.py runserver 0.0.0.0:8000
    command: ["sh", "start.sh", "db"]
    volumes:
      - $PWD/backend:/code
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET}
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend